//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooiasoft.InformacionTemaCicloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", ConfigurationName="InformacionTemaCicloWS.InformacionTemaCicloWS")]
    public interface InformacionTemaCicloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarTemaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.modificarTemaResponse modificarTema(ooiasoft.InformacionTemaCicloWS.modificarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarTemaResponse" +
            "")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarTemaResponse> modificarTemaAsync(ooiasoft.InformacionTemaCicloWS.modificarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.insertarTemaResponse insertarTema(ooiasoft.InformacionTemaCicloWS.insertarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarTemaResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarTemaResponse> insertarTemaAsync(ooiasoft.InformacionTemaCicloWS.insertarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse eliminarTema(ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarTemaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarTemaResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse> eliminarTemaAsync(ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarTemasRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarTemasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.listarTemasResponse listarTemas(ooiasoft.InformacionTemaCicloWS.listarTemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarTemasRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarTemasResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarTemasResponse> listarTemasAsync(ooiasoft.InformacionTemaCicloWS.listarTemasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarInformacionTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarInformacionTe" +
            "maCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse eliminarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarInformacionTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/eliminarInformacionTe" +
            "maCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse> eliminarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarInformacionTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarInformacionTe" +
            "maCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse insertarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarInformacionTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/insertarInformacionTe" +
            "maCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse> insertarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarInformacionesTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarInformacionesTe" +
            "maCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse listarInformacionesTemaCiclo(ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarInformacionesTe" +
            "maCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/listarInformacionesTe" +
            "maCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse> listarInformacionesTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarInformacionT" +
            "emaCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarInformacionT" +
            "emaCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse modificarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarInformacionT" +
            "emaCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/InformacionTemaCicloWS/modificarInformacionT" +
            "emaCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse> modificarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class tema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private int idTemaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTema {
            get {
                return this.idTemaField;
            }
            set {
                this.idTemaField = value;
                this.RaisePropertyChanged("idTema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCicloField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCiclo {
            get {
                return this.idCicloField;
            }
            set {
                this.idCicloField = value;
                this.RaisePropertyChanged("idCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class informacionTemaCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ciclo cicloField;
        
        private string descripcionField;
        
        private string descripcionUTFField;
        
        private bool estadoField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private System.DateTime fechaVisibleField;
        
        private bool fechaVisibleFieldSpecified;
        
        private byte[] fotoField;
        
        private int idInformacionTemaCicloField;
        
        private tema temaField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionUTF {
            get {
                return this.descripcionUTFField;
            }
            set {
                this.descripcionUTFField = value;
                this.RaisePropertyChanged("descripcionUTF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaVisible {
            get {
                return this.fechaVisibleField;
            }
            set {
                this.fechaVisibleField = value;
                this.RaisePropertyChanged("fechaVisible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVisibleSpecified {
            get {
                return this.fechaVisibleFieldSpecified;
            }
            set {
                this.fechaVisibleFieldSpecified = value;
                this.RaisePropertyChanged("fechaVisibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idInformacionTemaCiclo {
            get {
                return this.idInformacionTemaCicloField;
            }
            set {
                this.idInformacionTemaCicloField = value;
                this.RaisePropertyChanged("idInformacionTemaCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tema tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTema", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.tema tema;
        
        public modificarTemaRequest() {
        }
        
        public modificarTemaRequest(ooiasoft.InformacionTemaCicloWS.tema tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTemaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTemaResponse() {
        }
        
        public modificarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTema", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.tema tema;
        
        public insertarTemaRequest() {
        }
        
        public insertarTemaRequest(ooiasoft.InformacionTemaCicloWS.tema tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTemaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTemaResponse() {
        }
        
        public insertarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTema", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTema;
        
        public eliminarTemaRequest() {
        }
        
        public eliminarTemaRequest(int idTema) {
            this.idTema = idTema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTemaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTemaResponse() {
        }
        
        public eliminarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemas", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTemasRequest {
        
        public listarTemasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemasResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.tema[] @return;
        
        public listarTemasResponse() {
        }
        
        public listarTemasResponse(ooiasoft.InformacionTemaCicloWS.tema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInformacionTemaCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInformacionTemaCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idInfoTemaCiclo;
        
        public eliminarInformacionTemaCicloRequest() {
        }
        
        public eliminarInformacionTemaCicloRequest(int idInfoTemaCiclo) {
            this.idInfoTemaCiclo = idInfoTemaCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInformacionTemaCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInformacionTemaCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarInformacionTemaCicloResponse() {
        }
        
        public eliminarInformacionTemaCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInformacionTemaCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInformacionTemaCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo;
        
        public insertarInformacionTemaCicloRequest() {
        }
        
        public insertarInformacionTemaCicloRequest(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            this.infoTemaCiclo = infoTemaCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInformacionTemaCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInformacionTemaCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarInformacionTemaCicloResponse() {
        }
        
        public insertarInformacionTemaCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInformacionesTemaCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarInformacionesTemaCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCiclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTema;
        
        public listarInformacionesTemaCicloRequest() {
        }
        
        public listarInformacionesTemaCicloRequest(int idCiclo, int idTema) {
            this.idCiclo = idCiclo;
            this.idTema = idTema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInformacionesTemaCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarInformacionesTemaCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo[] @return;
        
        public listarInformacionesTemaCicloResponse() {
        }
        
        public listarInformacionesTemaCicloResponse(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarInformacionTemaCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarInformacionTemaCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo;
        
        public modificarInformacionTemaCicloRequest() {
        }
        
        public modificarInformacionTemaCicloRequest(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            this.infoTemaCiclo = infoTemaCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarInformacionTemaCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarInformacionTemaCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarInformacionTemaCicloResponse() {
        }
        
        public modificarInformacionTemaCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InformacionTemaCicloWSChannel : ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformacionTemaCicloWSClient : System.ServiceModel.ClientBase<ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS>, ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS {
        
        public InformacionTemaCicloWSClient() {
        }
        
        public InformacionTemaCicloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformacionTemaCicloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformacionTemaCicloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformacionTemaCicloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.modificarTemaResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.modificarTema(ooiasoft.InformacionTemaCicloWS.modificarTemaRequest request) {
            return base.Channel.modificarTema(request);
        }
        
        public int modificarTema(ooiasoft.InformacionTemaCicloWS.tema tema) {
            ooiasoft.InformacionTemaCicloWS.modificarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.modificarTemaRequest();
            inValue.tema = tema;
            ooiasoft.InformacionTemaCicloWS.modificarTemaResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).modificarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarTemaResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.modificarTemaAsync(ooiasoft.InformacionTemaCicloWS.modificarTemaRequest request) {
            return base.Channel.modificarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarTemaResponse> modificarTemaAsync(ooiasoft.InformacionTemaCicloWS.tema tema) {
            ooiasoft.InformacionTemaCicloWS.modificarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.modificarTemaRequest();
            inValue.tema = tema;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).modificarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.insertarTemaResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.insertarTema(ooiasoft.InformacionTemaCicloWS.insertarTemaRequest request) {
            return base.Channel.insertarTema(request);
        }
        
        public int insertarTema(ooiasoft.InformacionTemaCicloWS.tema tema) {
            ooiasoft.InformacionTemaCicloWS.insertarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.insertarTemaRequest();
            inValue.tema = tema;
            ooiasoft.InformacionTemaCicloWS.insertarTemaResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).insertarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarTemaResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.insertarTemaAsync(ooiasoft.InformacionTemaCicloWS.insertarTemaRequest request) {
            return base.Channel.insertarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarTemaResponse> insertarTemaAsync(ooiasoft.InformacionTemaCicloWS.tema tema) {
            ooiasoft.InformacionTemaCicloWS.insertarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.insertarTemaRequest();
            inValue.tema = tema;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).insertarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.eliminarTema(ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest request) {
            return base.Channel.eliminarTema(request);
        }
        
        public int eliminarTema(int idTema) {
            ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest();
            inValue.idTema = idTema;
            ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).eliminarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.eliminarTemaAsync(ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest request) {
            return base.Channel.eliminarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarTemaResponse> eliminarTemaAsync(int idTema) {
            ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest inValue = new ooiasoft.InformacionTemaCicloWS.eliminarTemaRequest();
            inValue.idTema = idTema;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).eliminarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.listarTemasResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.listarTemas(ooiasoft.InformacionTemaCicloWS.listarTemasRequest request) {
            return base.Channel.listarTemas(request);
        }
        
        public ooiasoft.InformacionTemaCicloWS.tema[] listarTemas() {
            ooiasoft.InformacionTemaCicloWS.listarTemasRequest inValue = new ooiasoft.InformacionTemaCicloWS.listarTemasRequest();
            ooiasoft.InformacionTemaCicloWS.listarTemasResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).listarTemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarTemasResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.listarTemasAsync(ooiasoft.InformacionTemaCicloWS.listarTemasRequest request) {
            return base.Channel.listarTemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarTemasResponse> listarTemasAsync() {
            ooiasoft.InformacionTemaCicloWS.listarTemasRequest inValue = new ooiasoft.InformacionTemaCicloWS.listarTemasRequest();
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).listarTemasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.eliminarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest request) {
            return base.Channel.eliminarInformacionTemaCiclo(request);
        }
        
        public int eliminarInformacionTemaCiclo(int idInfoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest();
            inValue.idInfoTemaCiclo = idInfoTemaCiclo;
            ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).eliminarInformacionTemaCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.eliminarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest request) {
            return base.Channel.eliminarInformacionTemaCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloResponse> eliminarInformacionTemaCicloAsync(int idInfoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.eliminarInformacionTemaCicloRequest();
            inValue.idInfoTemaCiclo = idInfoTemaCiclo;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).eliminarInformacionTemaCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.insertarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest request) {
            return base.Channel.insertarInformacionTemaCiclo(request);
        }
        
        public int insertarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest();
            inValue.infoTemaCiclo = infoTemaCiclo;
            ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).insertarInformacionTemaCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.insertarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest request) {
            return base.Channel.insertarInformacionTemaCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloResponse> insertarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.insertarInformacionTemaCicloRequest();
            inValue.infoTemaCiclo = infoTemaCiclo;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).insertarInformacionTemaCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.listarInformacionesTemaCiclo(ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest request) {
            return base.Channel.listarInformacionesTemaCiclo(request);
        }
        
        public ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo[] listarInformacionesTemaCiclo(int idCiclo, int idTema) {
            ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest();
            inValue.idCiclo = idCiclo;
            inValue.idTema = idTema;
            ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).listarInformacionesTemaCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.listarInformacionesTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest request) {
            return base.Channel.listarInformacionesTemaCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloResponse> listarInformacionesTemaCicloAsync(int idCiclo, int idTema) {
            ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.listarInformacionesTemaCicloRequest();
            inValue.idCiclo = idCiclo;
            inValue.idTema = idTema;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).listarInformacionesTemaCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.modificarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest request) {
            return base.Channel.modificarInformacionTemaCiclo(request);
        }
        
        public int modificarInformacionTemaCiclo(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest();
            inValue.infoTemaCiclo = infoTemaCiclo;
            ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse retVal = ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).modificarInformacionTemaCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse> ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS.modificarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest request) {
            return base.Channel.modificarInformacionTemaCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloResponse> modificarInformacionTemaCicloAsync(ooiasoft.InformacionTemaCicloWS.informacionTemaCiclo infoTemaCiclo) {
            ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest inValue = new ooiasoft.InformacionTemaCicloWS.modificarInformacionTemaCicloRequest();
            inValue.infoTemaCiclo = infoTemaCiclo;
            return ((ooiasoft.InformacionTemaCicloWS.InformacionTemaCicloWS)(this)).modificarInformacionTemaCicloAsync(inValue);
        }
    }
}
