//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooiasoft.EventoCicloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", ConfigurationName="EventoCicloWS.EventoCicloWS")]
    public interface EventoCicloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosParaAdminist" +
            "rativoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosParaAdminist" +
            "rativoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse listarEventoCiclosParaAdministrativo(ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosParaAdminist" +
            "rativoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosParaAdminist" +
            "rativoResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse> listarEventoCiclosParaAdministrativoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosInscritosPar" +
            "aAlumnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosInscritosPar" +
            "aAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse listarEventoCiclosInscritosParaAlumno(ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosInscritosPar" +
            "aAlumnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosInscritosPar" +
            "aAlumnoResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse> listarEventoCiclosInscritosParaAlumnoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosNoInscritosP" +
            "araAlumnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosNoInscritosP" +
            "araAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse listarEventoCiclosNoInscritosParaAlumno(ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosNoInscritosP" +
            "araAlumnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/listarEventoCiclosNoInscritosP" +
            "araAlumnoResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse> listarEventoCiclosNoInscritosParaAlumnoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/insertarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/insertarEventoCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.insertarEventoCicloResponse insertarEventoCiclo(ooiasoft.EventoCicloWS.insertarEventoCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/insertarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/insertarEventoCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.insertarEventoCicloResponse> insertarEventoCicloAsync(ooiasoft.EventoCicloWS.insertarEventoCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/inscribirAlumnoEventoCicloRequ" +
            "est", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/inscribirAlumnoEventoCicloResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse inscribirAlumnoEventoCiclo(ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/inscribirAlumnoEventoCicloRequ" +
            "est", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/inscribirAlumnoEventoCicloResp" +
            "onse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse> inscribirAlumnoEventoCicloAsync(ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/modificarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/modificarEventoCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.modificarEventoCicloResponse modificarEventoCiclo(ooiasoft.EventoCicloWS.modificarEventoCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/modificarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/modificarEventoCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.modificarEventoCicloResponse> modificarEventoCicloAsync(ooiasoft.EventoCicloWS.modificarEventoCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/eliminarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/eliminarEventoCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.eliminarEventoCicloResponse eliminarEventoCiclo(ooiasoft.EventoCicloWS.eliminarEventoCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/eliminarEventoCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/eliminarEventoCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.eliminarEventoCicloResponse> eliminarEventoCicloAsync(ooiasoft.EventoCicloWS.eliminarEventoCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/desinscribirAlumnoEventoCicloR" +
            "equest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/desinscribirAlumnoEventoCicloR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse desinscribirAlumnoEventoCiclo(ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/desinscribirAlumnoEventoCicloR" +
            "equest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/EventoCicloWS/desinscribirAlumnoEventoCicloR" +
            "esponse")]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse> desinscribirAlumnoEventoCicloAsync(ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class eventoCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno[] alumnosInscritosField;
        
        private string aulaField;
        
        private int cantAsistentesField;
        
        private int capacidadMaxField;
        
        private ciclo cicloField;
        
        private string descripcionField;
        
        private string descripcionUTFField;
        
        private int duracionHorasField;
        
        private bool estadoField;
        
        private estadoEvento estadoEventoField;
        
        private bool estadoEventoFieldSpecified;
        
        private System.DateTime fechaEventoField;
        
        private bool fechaEventoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private byte[] fotoField;
        
        private int horaIniField;
        
        private int idEventoCicloField;
        
        private string linkEncuestaSatisfaccionField;
        
        private string linkVideoField;
        
        private string organizadoresField;
        
        private string tituloField;
        
        private string tituloUTFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alumnosInscritos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public alumno[] alumnosInscritos {
            get {
                return this.alumnosInscritosField;
            }
            set {
                this.alumnosInscritosField = value;
                this.RaisePropertyChanged("alumnosInscritos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string aula {
            get {
                return this.aulaField;
            }
            set {
                this.aulaField = value;
                this.RaisePropertyChanged("aula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantAsistentes {
            get {
                return this.cantAsistentesField;
            }
            set {
                this.cantAsistentesField = value;
                this.RaisePropertyChanged("cantAsistentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int capacidadMax {
            get {
                return this.capacidadMaxField;
            }
            set {
                this.capacidadMaxField = value;
                this.RaisePropertyChanged("capacidadMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string descripcionUTF {
            get {
                return this.descripcionUTFField;
            }
            set {
                this.descripcionUTFField = value;
                this.RaisePropertyChanged("descripcionUTF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int duracionHoras {
            get {
                return this.duracionHorasField;
            }
            set {
                this.duracionHorasField = value;
                this.RaisePropertyChanged("duracionHoras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public estadoEvento estadoEvento {
            get {
                return this.estadoEventoField;
            }
            set {
                this.estadoEventoField = value;
                this.RaisePropertyChanged("estadoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoEventoSpecified {
            get {
                return this.estadoEventoFieldSpecified;
            }
            set {
                this.estadoEventoFieldSpecified = value;
                this.RaisePropertyChanged("estadoEventoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime fechaEvento {
            get {
                return this.fechaEventoField;
            }
            set {
                this.fechaEventoField = value;
                this.RaisePropertyChanged("fechaEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEventoSpecified {
            get {
                return this.fechaEventoFieldSpecified;
            }
            set {
                this.fechaEventoFieldSpecified = value;
                this.RaisePropertyChanged("fechaEventoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=12)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int horaIni {
            get {
                return this.horaIniField;
            }
            set {
                this.horaIniField = value;
                this.RaisePropertyChanged("horaIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int idEventoCiclo {
            get {
                return this.idEventoCicloField;
            }
            set {
                this.idEventoCicloField = value;
                this.RaisePropertyChanged("idEventoCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string linkEncuestaSatisfaccion {
            get {
                return this.linkEncuestaSatisfaccionField;
            }
            set {
                this.linkEncuestaSatisfaccionField = value;
                this.RaisePropertyChanged("linkEncuestaSatisfaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string linkVideo {
            get {
                return this.linkVideoField;
            }
            set {
                this.linkVideoField = value;
                this.RaisePropertyChanged("linkVideo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string organizadores {
            get {
                return this.organizadoresField;
            }
            set {
                this.organizadoresField = value;
                this.RaisePropertyChanged("organizadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string tituloUTF {
            get {
                return this.tituloUTFField;
            }
            set {
                this.tituloUTFField = value;
                this.RaisePropertyChanged("tituloUTF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumno : persona {
        
        private double cRAESTField;
        
        private int cantCiclosField;
        
        private int cantCursosAprobadosField;
        
        private double cantidadCreditosAprobadosField;
        
        private alumnoCiclo[] ciclosField;
        
        private int escalaPagoField;
        
        private especialidad especialidadField;
        
        private double promedioPonderadoField;
        
        private tipoAlumno tipoField;
        
        private bool tipoFieldSpecified;
        
        private double totalCreditosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double CRAEST {
            get {
                return this.cRAESTField;
            }
            set {
                this.cRAESTField = value;
                this.RaisePropertyChanged("CRAEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantCiclos {
            get {
                return this.cantCiclosField;
            }
            set {
                this.cantCiclosField = value;
                this.RaisePropertyChanged("cantCiclos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantCursosAprobados {
            get {
                return this.cantCursosAprobadosField;
            }
            set {
                this.cantCursosAprobadosField = value;
                this.RaisePropertyChanged("cantCursosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double cantidadCreditosAprobados {
            get {
                return this.cantidadCreditosAprobadosField;
            }
            set {
                this.cantidadCreditosAprobadosField = value;
                this.RaisePropertyChanged("cantidadCreditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ciclos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public alumnoCiclo[] ciclos {
            get {
                return this.ciclosField;
            }
            set {
                this.ciclosField = value;
                this.RaisePropertyChanged("ciclos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int escalaPago {
            get {
                return this.escalaPagoField;
            }
            set {
                this.escalaPagoField = value;
                this.RaisePropertyChanged("escalaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double promedioPonderado {
            get {
                return this.promedioPonderadoField;
            }
            set {
                this.promedioPonderadoField = value;
                this.RaisePropertyChanged("promedioPonderado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoAlumno tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double totalCreditos {
            get {
                return this.totalCreditosField;
            }
            set {
                this.totalCreditosField = value;
                this.RaisePropertyChanged("totalCreditos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumnoCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double cRAESTField;
        
        private int cantidadCursosAprobadosField;
        
        private ciclo cicloField;
        
        private double creditosAprobadosField;
        
        private double creditosTotalesField;
        
        private alumnoCursoCiclo[] cursosField;
        
        private bool estadoField;
        
        private int idAlumnoCicloField;
        
        private double promedioPonderadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double CRAEST {
            get {
                return this.cRAESTField;
            }
            set {
                this.cRAESTField = value;
                this.RaisePropertyChanged("CRAEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadCursosAprobados {
            get {
                return this.cantidadCursosAprobadosField;
            }
            set {
                this.cantidadCursosAprobadosField = value;
                this.RaisePropertyChanged("cantidadCursosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double creditosAprobados {
            get {
                return this.creditosAprobadosField;
            }
            set {
                this.creditosAprobadosField = value;
                this.RaisePropertyChanged("creditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double creditosTotales {
            get {
                return this.creditosTotalesField;
            }
            set {
                this.creditosTotalesField = value;
                this.RaisePropertyChanged("creditosTotales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public alumnoCursoCiclo[] cursos {
            get {
                return this.cursosField;
            }
            set {
                this.cursosField = value;
                this.RaisePropertyChanged("cursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idAlumnoCiclo {
            get {
                return this.idAlumnoCicloField;
            }
            set {
                this.idAlumnoCicloField = value;
                this.RaisePropertyChanged("idAlumnoCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double promedioPonderado {
            get {
                return this.promedioPonderadoField;
            }
            set {
                this.promedioPonderadoField = value;
                this.RaisePropertyChanged("promedioPonderado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCicloField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCiclo {
            get {
                return this.idCicloField;
            }
            set {
                this.idCicloField = value;
                this.RaisePropertyChanged("idCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class evaluacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comentariosField;
        
        private bool estadoField;
        
        private int idEvaluacionField;
        
        private int notaField;
        
        private int numEvaluacionField;
        
        private tipoEvaluacion tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEvaluacion {
            get {
                return this.idEvaluacionField;
            }
            set {
                this.idEvaluacionField = value;
                this.RaisePropertyChanged("idEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
                this.RaisePropertyChanged("nota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numEvaluacion {
            get {
                return this.numEvaluacionField;
            }
            set {
                this.numEvaluacionField = value;
                this.RaisePropertyChanged("numEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoEvaluacion tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoEvaluacion {
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        EX,
        
        /// <remarks/>
        TA,
        
        /// <remarks/>
        PC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private bool estadoField;
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private double creditosField;
        
        private especialidad especialidadField;
        
        private bool estadoField;
        
        private int idCursoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumnoCursoCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private curso cursoField;
        
        private tipoECTS escalaField;
        
        private bool escalaFieldSpecified;
        
        private bool estadoField;
        
        private evaluacion[] evaluacionesField;
        
        private int idAlumnoCursoCicloField;
        
        private double notaFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoECTS escala {
            get {
                return this.escalaField;
            }
            set {
                this.escalaField = value;
                this.RaisePropertyChanged("escala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool escalaSpecified {
            get {
                return this.escalaFieldSpecified;
            }
            set {
                this.escalaFieldSpecified = value;
                this.RaisePropertyChanged("escalaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public evaluacion[] evaluaciones {
            get {
                return this.evaluacionesField;
            }
            set {
                this.evaluacionesField = value;
                this.RaisePropertyChanged("evaluaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idAlumnoCursoCiclo {
            get {
                return this.idAlumnoCursoCicloField;
            }
            set {
                this.idAlumnoCursoCicloField = value;
                this.RaisePropertyChanged("idAlumnoCursoCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double notaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
                this.RaisePropertyChanged("notaFinal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoECTS {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        FX,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        NT,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPUCPField;
        
        private string correoField;
        
        private string dNIField;
        
        private int edadField;
        
        private bool estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombreCompletoField;
        
        private string passwordField;
        
        private ushort sexoField;
        
        private string telefonoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoAlumno {
        
        /// <remarks/>
        Regular,
        
        /// <remarks/>
        NoRegular,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum estadoEvento {
        
        /// <remarks/>
        Pendiente,
        
        /// <remarks/>
        Pasado,
        
        /// <remarks/>
        Cancelado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosParaAdministrativo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosParaAdministrativoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ciclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public listarEventoCiclosParaAdministrativoRequest() {
        }
        
        public listarEventoCiclosParaAdministrativoRequest(string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            this.ciclo = ciclo;
            this.nombre = nombre;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosParaAdministrativoResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosParaAdministrativoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.EventoCicloWS.eventoCiclo[] @return;
        
        public listarEventoCiclosParaAdministrativoResponse() {
        }
        
        public listarEventoCiclosParaAdministrativoResponse(ooiasoft.EventoCicloWS.eventoCiclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosInscritosParaAlumno", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosInscritosParaAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ciclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public listarEventoCiclosInscritosParaAlumnoRequest() {
        }
        
        public listarEventoCiclosInscritosParaAlumnoRequest(int idAlumno, string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            this.idAlumno = idAlumno;
            this.ciclo = ciclo;
            this.nombre = nombre;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosInscritosParaAlumnoResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosInscritosParaAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.EventoCicloWS.eventoCiclo[] @return;
        
        public listarEventoCiclosInscritosParaAlumnoResponse() {
        }
        
        public listarEventoCiclosInscritosParaAlumnoResponse(ooiasoft.EventoCicloWS.eventoCiclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosNoInscritosParaAlumno", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosNoInscritosParaAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCiclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        public listarEventoCiclosNoInscritosParaAlumnoRequest() {
        }
        
        public listarEventoCiclosNoInscritosParaAlumnoRequest(int idAlumno, int idCiclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin) {
            this.idAlumno = idAlumno;
            this.idCiclo = idCiclo;
            this.nombre = nombre;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoCiclosNoInscritosParaAlumnoResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventoCiclosNoInscritosParaAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.EventoCicloWS.eventoCiclo[] @return;
        
        public listarEventoCiclosNoInscritosParaAlumnoResponse() {
        }
        
        public listarEventoCiclosNoInscritosParaAlumnoResponse(ooiasoft.EventoCicloWS.eventoCiclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo;
        
        public insertarEventoCicloRequest() {
        }
        
        public insertarEventoCicloRequest(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            this.eventoCiclo = eventoCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEventoCicloResponse() {
        }
        
        public insertarEventoCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inscribirAlumnoEventoCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class inscribirAlumnoEventoCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEventoCiclo;
        
        public inscribirAlumnoEventoCicloRequest() {
        }
        
        public inscribirAlumnoEventoCicloRequest(int idAlumno, int idEventoCiclo) {
            this.idAlumno = idAlumno;
            this.idEventoCiclo = idEventoCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inscribirAlumnoEventoCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class inscribirAlumnoEventoCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public inscribirAlumnoEventoCicloResponse() {
        }
        
        public inscribirAlumnoEventoCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEventoCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEventoCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo;
        
        public modificarEventoCicloRequest() {
        }
        
        public modificarEventoCicloRequest(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            this.eventoCiclo = eventoCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEventoCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEventoCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEventoCicloResponse() {
        }
        
        public modificarEventoCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEventoCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEventoCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEventoCiclo;
        
        public eliminarEventoCicloRequest() {
        }
        
        public eliminarEventoCicloRequest(int idEventoCiclo) {
            this.idEventoCiclo = idEventoCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEventoCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEventoCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEventoCicloResponse() {
        }
        
        public eliminarEventoCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desinscribirAlumnoEventoCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class desinscribirAlumnoEventoCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEventoCiclo;
        
        public desinscribirAlumnoEventoCicloRequest() {
        }
        
        public desinscribirAlumnoEventoCicloRequest(int idAlumno, int idEventoCiclo) {
            this.idAlumno = idAlumno;
            this.idEventoCiclo = idEventoCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desinscribirAlumnoEventoCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class desinscribirAlumnoEventoCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public desinscribirAlumnoEventoCicloResponse() {
        }
        
        public desinscribirAlumnoEventoCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventoCicloWSChannel : ooiasoft.EventoCicloWS.EventoCicloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoCicloWSClient : System.ServiceModel.ClientBase<ooiasoft.EventoCicloWS.EventoCicloWS>, ooiasoft.EventoCicloWS.EventoCicloWS {
        
        public EventoCicloWSClient() {
        }
        
        public EventoCicloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventoCicloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoCicloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoCicloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosParaAdministrativo(ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest request) {
            return base.Channel.listarEventoCiclosParaAdministrativo(request);
        }
        
        public ooiasoft.EventoCicloWS.eventoCiclo[] listarEventoCiclosParaAdministrativo(string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest();
            inValue.ciclo = ciclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosParaAdministrativo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse> ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosParaAdministrativoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest request) {
            return base.Channel.listarEventoCiclosParaAdministrativoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoResponse> listarEventoCiclosParaAdministrativoAsync(string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosParaAdministrativoRequest();
            inValue.ciclo = ciclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosParaAdministrativoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosInscritosParaAlumno(ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest request) {
            return base.Channel.listarEventoCiclosInscritosParaAlumno(request);
        }
        
        public ooiasoft.EventoCicloWS.eventoCiclo[] listarEventoCiclosInscritosParaAlumno(int idAlumno, string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest();
            inValue.idAlumno = idAlumno;
            inValue.ciclo = ciclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosInscritosParaAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse> ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest request) {
            return base.Channel.listarEventoCiclosInscritosParaAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoResponse> listarEventoCiclosInscritosParaAlumnoAsync(int idAlumno, string ciclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin, string estado) {
            ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosInscritosParaAlumnoRequest();
            inValue.idAlumno = idAlumno;
            inValue.ciclo = ciclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosInscritosParaAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumno(ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest request) {
            return base.Channel.listarEventoCiclosNoInscritosParaAlumno(request);
        }
        
        public ooiasoft.EventoCicloWS.eventoCiclo[] listarEventoCiclosNoInscritosParaAlumno(int idAlumno, int idCiclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin) {
            ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest();
            inValue.idAlumno = idAlumno;
            inValue.idCiclo = idCiclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosNoInscritosParaAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse> ooiasoft.EventoCicloWS.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoAsync(ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest request) {
            return base.Channel.listarEventoCiclosNoInscritosParaAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoResponse> listarEventoCiclosNoInscritosParaAlumnoAsync(int idAlumno, int idCiclo, string nombre, System.DateTime fechaIni, System.DateTime fechaFin) {
            ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest inValue = new ooiasoft.EventoCicloWS.listarEventoCiclosNoInscritosParaAlumnoRequest();
            inValue.idAlumno = idAlumno;
            inValue.idCiclo = idCiclo;
            inValue.nombre = nombre;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).listarEventoCiclosNoInscritosParaAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.insertarEventoCicloResponse ooiasoft.EventoCicloWS.EventoCicloWS.insertarEventoCiclo(ooiasoft.EventoCicloWS.insertarEventoCicloRequest request) {
            return base.Channel.insertarEventoCiclo(request);
        }
        
        public int insertarEventoCiclo(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            ooiasoft.EventoCicloWS.insertarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.insertarEventoCicloRequest();
            inValue.eventoCiclo = eventoCiclo;
            ooiasoft.EventoCicloWS.insertarEventoCicloResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).insertarEventoCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.insertarEventoCicloResponse> ooiasoft.EventoCicloWS.EventoCicloWS.insertarEventoCicloAsync(ooiasoft.EventoCicloWS.insertarEventoCicloRequest request) {
            return base.Channel.insertarEventoCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.insertarEventoCicloResponse> insertarEventoCicloAsync(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            ooiasoft.EventoCicloWS.insertarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.insertarEventoCicloRequest();
            inValue.eventoCiclo = eventoCiclo;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).insertarEventoCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse ooiasoft.EventoCicloWS.EventoCicloWS.inscribirAlumnoEventoCiclo(ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest request) {
            return base.Channel.inscribirAlumnoEventoCiclo(request);
        }
        
        public int inscribirAlumnoEventoCiclo(int idAlumno, int idEventoCiclo) {
            ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest();
            inValue.idAlumno = idAlumno;
            inValue.idEventoCiclo = idEventoCiclo;
            ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).inscribirAlumnoEventoCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse> ooiasoft.EventoCicloWS.EventoCicloWS.inscribirAlumnoEventoCicloAsync(ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest request) {
            return base.Channel.inscribirAlumnoEventoCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloResponse> inscribirAlumnoEventoCicloAsync(int idAlumno, int idEventoCiclo) {
            ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.inscribirAlumnoEventoCicloRequest();
            inValue.idAlumno = idAlumno;
            inValue.idEventoCiclo = idEventoCiclo;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).inscribirAlumnoEventoCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.modificarEventoCicloResponse ooiasoft.EventoCicloWS.EventoCicloWS.modificarEventoCiclo(ooiasoft.EventoCicloWS.modificarEventoCicloRequest request) {
            return base.Channel.modificarEventoCiclo(request);
        }
        
        public int modificarEventoCiclo(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            ooiasoft.EventoCicloWS.modificarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.modificarEventoCicloRequest();
            inValue.eventoCiclo = eventoCiclo;
            ooiasoft.EventoCicloWS.modificarEventoCicloResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).modificarEventoCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.modificarEventoCicloResponse> ooiasoft.EventoCicloWS.EventoCicloWS.modificarEventoCicloAsync(ooiasoft.EventoCicloWS.modificarEventoCicloRequest request) {
            return base.Channel.modificarEventoCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.modificarEventoCicloResponse> modificarEventoCicloAsync(ooiasoft.EventoCicloWS.eventoCiclo eventoCiclo) {
            ooiasoft.EventoCicloWS.modificarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.modificarEventoCicloRequest();
            inValue.eventoCiclo = eventoCiclo;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).modificarEventoCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.eliminarEventoCicloResponse ooiasoft.EventoCicloWS.EventoCicloWS.eliminarEventoCiclo(ooiasoft.EventoCicloWS.eliminarEventoCicloRequest request) {
            return base.Channel.eliminarEventoCiclo(request);
        }
        
        public int eliminarEventoCiclo(int idEventoCiclo) {
            ooiasoft.EventoCicloWS.eliminarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.eliminarEventoCicloRequest();
            inValue.idEventoCiclo = idEventoCiclo;
            ooiasoft.EventoCicloWS.eliminarEventoCicloResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).eliminarEventoCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.eliminarEventoCicloResponse> ooiasoft.EventoCicloWS.EventoCicloWS.eliminarEventoCicloAsync(ooiasoft.EventoCicloWS.eliminarEventoCicloRequest request) {
            return base.Channel.eliminarEventoCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.eliminarEventoCicloResponse> eliminarEventoCicloAsync(int idEventoCiclo) {
            ooiasoft.EventoCicloWS.eliminarEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.eliminarEventoCicloRequest();
            inValue.idEventoCiclo = idEventoCiclo;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).eliminarEventoCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse ooiasoft.EventoCicloWS.EventoCicloWS.desinscribirAlumnoEventoCiclo(ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest request) {
            return base.Channel.desinscribirAlumnoEventoCiclo(request);
        }
        
        public int desinscribirAlumnoEventoCiclo(int idAlumno, int idEventoCiclo) {
            ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest();
            inValue.idAlumno = idAlumno;
            inValue.idEventoCiclo = idEventoCiclo;
            ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse retVal = ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).desinscribirAlumnoEventoCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse> ooiasoft.EventoCicloWS.EventoCicloWS.desinscribirAlumnoEventoCicloAsync(ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest request) {
            return base.Channel.desinscribirAlumnoEventoCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloResponse> desinscribirAlumnoEventoCicloAsync(int idAlumno, int idEventoCiclo) {
            ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest inValue = new ooiasoft.EventoCicloWS.desinscribirAlumnoEventoCicloRequest();
            inValue.idAlumno = idAlumno;
            inValue.idEventoCiclo = idEventoCiclo;
            return ((ooiasoft.EventoCicloWS.EventoCicloWS)(this)).desinscribirAlumnoEventoCicloAsync(inValue);
        }
    }
}
