//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooiasoft.HorarioCicloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", ConfigurationName="HorarioCicloWS.HorarioCicloWS")]
    public interface HorarioCicloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/listarHorarioCiclosRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/listarHorarioCiclosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse listarHorarioCiclos(ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/listarHorarioCiclosRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/listarHorarioCiclosResponse")]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse> listarHorarioCiclosAsync(ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/modificarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/modificarHorarioCicloResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse modificarHorarioCiclo(ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/modificarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/modificarHorarioCicloResponse" +
            "")]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse> modificarHorarioCicloAsync(ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/eliminarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/eliminarHorarioCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse eliminarHorarioCiclo(ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/eliminarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/eliminarHorarioCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse> eliminarHorarioCicloAsync(ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/insertarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/insertarHorarioCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse insertarHorarioCiclo(ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/insertarHorarioCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/HorarioCicloWS/insertarHorarioCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse> insertarHorarioCicloAsync(ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class horarioCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ciclo cicloField;
        
        private bool estadoField;
        
        private detalleHorario[] horarioField;
        
        private int horasAtendidasField;
        
        private int horasDisponibleField;
        
        private int idHorarioCicloField;
        
        private personalCitas personalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public detalleHorario[] horario {
            get {
                return this.horarioField;
            }
            set {
                this.horarioField = value;
                this.RaisePropertyChanged("horario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int horasAtendidas {
            get {
                return this.horasAtendidasField;
            }
            set {
                this.horasAtendidasField = value;
                this.RaisePropertyChanged("horasAtendidas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int horasDisponible {
            get {
                return this.horasDisponibleField;
            }
            set {
                this.horasDisponibleField = value;
                this.RaisePropertyChanged("horasDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idHorarioCiclo {
            get {
                return this.idHorarioCicloField;
            }
            set {
                this.idHorarioCicloField = value;
                this.RaisePropertyChanged("idHorarioCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public personalCitas personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
                this.RaisePropertyChanged("personal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCicloField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCiclo {
            get {
                return this.idCicloField;
            }
            set {
                this.idCicloField = value;
                this.RaisePropertyChanged("idCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroOOIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personalCitas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPUCPField;
        
        private string correoField;
        
        private string dNIField;
        
        private int edadField;
        
        private bool estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombreCompletoField;
        
        private string passwordField;
        
        private ushort sexoField;
        
        private string telefonoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personalCitas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class miembroOOIA : persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class personalCitas : miembroOOIA {
        
        private int horasSemanalesField;
        
        private double rendimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int horasSemanales {
            get {
                return this.horasSemanalesField;
            }
            set {
                this.horasSemanalesField = value;
                this.RaisePropertyChanged("horasSemanales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double rendimiento {
            get {
                return this.rendimientoField;
            }
            set {
                this.rendimientoField = value;
                this.RaisePropertyChanged("rendimiento");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class detalleHorario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int diaField;
        
        private bool estadoField;
        
        private int horaFinField;
        
        private int horaInicioField;
        
        private int idDetalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idDetalle {
            get {
                return this.idDetalleField;
            }
            set {
                this.idDetalleField = value;
                this.RaisePropertyChanged("idDetalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHorarioCiclos", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarHorarioCiclosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersonalCitas;
        
        public listarHorarioCiclosRequest() {
        }
        
        public listarHorarioCiclosRequest(int idPersonalCitas) {
            this.idPersonalCitas = idPersonalCitas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHorarioCiclosResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarHorarioCiclosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.HorarioCicloWS.horarioCiclo[] @return;
        
        public listarHorarioCiclosResponse() {
        }
        
        public listarHorarioCiclosResponse(ooiasoft.HorarioCicloWS.horarioCiclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorarioCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorarioCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.HorarioCicloWS.horarioCiclo horario;
        
        public modificarHorarioCicloRequest() {
        }
        
        public modificarHorarioCicloRequest(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            this.horario = horario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorarioCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorarioCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarHorarioCicloResponse() {
        }
        
        public modificarHorarioCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarHorarioCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarHorarioCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idHorarioCiclo;
        
        public eliminarHorarioCicloRequest() {
        }
        
        public eliminarHorarioCicloRequest(int idHorarioCiclo) {
            this.idHorarioCiclo = idHorarioCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarHorarioCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarHorarioCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarHorarioCicloResponse() {
        }
        
        public eliminarHorarioCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorarioCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorarioCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.HorarioCicloWS.horarioCiclo horario;
        
        public insertarHorarioCicloRequest() {
        }
        
        public insertarHorarioCicloRequest(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            this.horario = horario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorarioCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorarioCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarHorarioCicloResponse() {
        }
        
        public insertarHorarioCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HorarioCicloWSChannel : ooiasoft.HorarioCicloWS.HorarioCicloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioCicloWSClient : System.ServiceModel.ClientBase<ooiasoft.HorarioCicloWS.HorarioCicloWS>, ooiasoft.HorarioCicloWS.HorarioCicloWS {
        
        public HorarioCicloWSClient() {
        }
        
        public HorarioCicloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioCicloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioCicloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioCicloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse ooiasoft.HorarioCicloWS.HorarioCicloWS.listarHorarioCiclos(ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest request) {
            return base.Channel.listarHorarioCiclos(request);
        }
        
        public ooiasoft.HorarioCicloWS.horarioCiclo[] listarHorarioCiclos(int idPersonalCitas) {
            ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest inValue = new ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest();
            inValue.idPersonalCitas = idPersonalCitas;
            ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse retVal = ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).listarHorarioCiclos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse> ooiasoft.HorarioCicloWS.HorarioCicloWS.listarHorarioCiclosAsync(ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest request) {
            return base.Channel.listarHorarioCiclosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.listarHorarioCiclosResponse> listarHorarioCiclosAsync(int idPersonalCitas) {
            ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest inValue = new ooiasoft.HorarioCicloWS.listarHorarioCiclosRequest();
            inValue.idPersonalCitas = idPersonalCitas;
            return ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).listarHorarioCiclosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse ooiasoft.HorarioCicloWS.HorarioCicloWS.modificarHorarioCiclo(ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest request) {
            return base.Channel.modificarHorarioCiclo(request);
        }
        
        public int modificarHorarioCiclo(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest();
            inValue.horario = horario;
            ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse retVal = ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).modificarHorarioCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse> ooiasoft.HorarioCicloWS.HorarioCicloWS.modificarHorarioCicloAsync(ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest request) {
            return base.Channel.modificarHorarioCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.modificarHorarioCicloResponse> modificarHorarioCicloAsync(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.modificarHorarioCicloRequest();
            inValue.horario = horario;
            return ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).modificarHorarioCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse ooiasoft.HorarioCicloWS.HorarioCicloWS.eliminarHorarioCiclo(ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest request) {
            return base.Channel.eliminarHorarioCiclo(request);
        }
        
        public int eliminarHorarioCiclo(int idHorarioCiclo) {
            ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest();
            inValue.idHorarioCiclo = idHorarioCiclo;
            ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse retVal = ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).eliminarHorarioCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse> ooiasoft.HorarioCicloWS.HorarioCicloWS.eliminarHorarioCicloAsync(ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest request) {
            return base.Channel.eliminarHorarioCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.eliminarHorarioCicloResponse> eliminarHorarioCicloAsync(int idHorarioCiclo) {
            ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.eliminarHorarioCicloRequest();
            inValue.idHorarioCiclo = idHorarioCiclo;
            return ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).eliminarHorarioCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse ooiasoft.HorarioCicloWS.HorarioCicloWS.insertarHorarioCiclo(ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest request) {
            return base.Channel.insertarHorarioCiclo(request);
        }
        
        public int insertarHorarioCiclo(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest();
            inValue.horario = horario;
            ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse retVal = ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).insertarHorarioCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse> ooiasoft.HorarioCicloWS.HorarioCicloWS.insertarHorarioCicloAsync(ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest request) {
            return base.Channel.insertarHorarioCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.HorarioCicloWS.insertarHorarioCicloResponse> insertarHorarioCicloAsync(ooiasoft.HorarioCicloWS.horarioCiclo horario) {
            ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest inValue = new ooiasoft.HorarioCicloWS.insertarHorarioCicloRequest();
            inValue.horario = horario;
            return ((ooiasoft.HorarioCicloWS.HorarioCicloWS)(this)).insertarHorarioCicloAsync(inValue);
        }
    }
}
