//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooiasoft.CicloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", ConfigurationName="CicloWS.CicloWS")]
    public interface CicloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/listarCiclosRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/listarCiclosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CicloWS.listarCiclosResponse listarCiclos(ooiasoft.CicloWS.listarCiclosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/listarCiclosRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/listarCiclosResponse")]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.listarCiclosResponse> listarCiclosAsync(ooiasoft.CicloWS.listarCiclosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/modificarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/modificarCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CicloWS.modificarCicloResponse modificarCiclo(ooiasoft.CicloWS.modificarCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/modificarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/modificarCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.modificarCicloResponse> modificarCicloAsync(ooiasoft.CicloWS.modificarCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/insertarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/insertarCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CicloWS.insertarCicloResponse insertarCiclo(ooiasoft.CicloWS.insertarCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/insertarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/insertarCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.insertarCicloResponse> insertarCicloAsync(ooiasoft.CicloWS.insertarCicloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/eliminarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/eliminarCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CicloWS.eliminarCicloResponse eliminarCiclo(ooiasoft.CicloWS.eliminarCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CicloWS/eliminarCicloRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CicloWS/eliminarCicloResponse")]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.eliminarCicloResponse> eliminarCicloAsync(ooiasoft.CicloWS.eliminarCicloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCicloField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCiclo {
            get {
                return this.idCicloField;
            }
            set {
                this.idCicloField = value;
                this.RaisePropertyChanged("idCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCiclos", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCiclosRequest {
        
        public listarCiclosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCiclosResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCiclosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CicloWS.ciclo[] @return;
        
        public listarCiclosResponse() {
        }
        
        public listarCiclosResponse(ooiasoft.CicloWS.ciclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CicloWS.ciclo ciclo;
        
        public modificarCicloRequest() {
        }
        
        public modificarCicloRequest(ooiasoft.CicloWS.ciclo ciclo) {
            this.ciclo = ciclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCicloResponse() {
        }
        
        public modificarCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CicloWS.ciclo ciclo;
        
        public insertarCicloRequest() {
        }
        
        public insertarCicloRequest(ooiasoft.CicloWS.ciclo ciclo) {
            this.ciclo = ciclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCicloResponse() {
        }
        
        public insertarCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCiclo", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCiclo;
        
        public eliminarCicloRequest() {
        }
        
        public eliminarCicloRequest(int idCiclo) {
            this.idCiclo = idCiclo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCicloResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCicloResponse() {
        }
        
        public eliminarCicloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CicloWSChannel : ooiasoft.CicloWS.CicloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CicloWSClient : System.ServiceModel.ClientBase<ooiasoft.CicloWS.CicloWS>, ooiasoft.CicloWS.CicloWS {
        
        public CicloWSClient() {
        }
        
        public CicloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CicloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CicloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CicloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CicloWS.listarCiclosResponse ooiasoft.CicloWS.CicloWS.listarCiclos(ooiasoft.CicloWS.listarCiclosRequest request) {
            return base.Channel.listarCiclos(request);
        }
        
        public ooiasoft.CicloWS.ciclo[] listarCiclos() {
            ooiasoft.CicloWS.listarCiclosRequest inValue = new ooiasoft.CicloWS.listarCiclosRequest();
            ooiasoft.CicloWS.listarCiclosResponse retVal = ((ooiasoft.CicloWS.CicloWS)(this)).listarCiclos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.listarCiclosResponse> ooiasoft.CicloWS.CicloWS.listarCiclosAsync(ooiasoft.CicloWS.listarCiclosRequest request) {
            return base.Channel.listarCiclosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CicloWS.listarCiclosResponse> listarCiclosAsync() {
            ooiasoft.CicloWS.listarCiclosRequest inValue = new ooiasoft.CicloWS.listarCiclosRequest();
            return ((ooiasoft.CicloWS.CicloWS)(this)).listarCiclosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CicloWS.modificarCicloResponse ooiasoft.CicloWS.CicloWS.modificarCiclo(ooiasoft.CicloWS.modificarCicloRequest request) {
            return base.Channel.modificarCiclo(request);
        }
        
        public int modificarCiclo(ooiasoft.CicloWS.ciclo ciclo) {
            ooiasoft.CicloWS.modificarCicloRequest inValue = new ooiasoft.CicloWS.modificarCicloRequest();
            inValue.ciclo = ciclo;
            ooiasoft.CicloWS.modificarCicloResponse retVal = ((ooiasoft.CicloWS.CicloWS)(this)).modificarCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.modificarCicloResponse> ooiasoft.CicloWS.CicloWS.modificarCicloAsync(ooiasoft.CicloWS.modificarCicloRequest request) {
            return base.Channel.modificarCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CicloWS.modificarCicloResponse> modificarCicloAsync(ooiasoft.CicloWS.ciclo ciclo) {
            ooiasoft.CicloWS.modificarCicloRequest inValue = new ooiasoft.CicloWS.modificarCicloRequest();
            inValue.ciclo = ciclo;
            return ((ooiasoft.CicloWS.CicloWS)(this)).modificarCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CicloWS.insertarCicloResponse ooiasoft.CicloWS.CicloWS.insertarCiclo(ooiasoft.CicloWS.insertarCicloRequest request) {
            return base.Channel.insertarCiclo(request);
        }
        
        public int insertarCiclo(ooiasoft.CicloWS.ciclo ciclo) {
            ooiasoft.CicloWS.insertarCicloRequest inValue = new ooiasoft.CicloWS.insertarCicloRequest();
            inValue.ciclo = ciclo;
            ooiasoft.CicloWS.insertarCicloResponse retVal = ((ooiasoft.CicloWS.CicloWS)(this)).insertarCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.insertarCicloResponse> ooiasoft.CicloWS.CicloWS.insertarCicloAsync(ooiasoft.CicloWS.insertarCicloRequest request) {
            return base.Channel.insertarCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CicloWS.insertarCicloResponse> insertarCicloAsync(ooiasoft.CicloWS.ciclo ciclo) {
            ooiasoft.CicloWS.insertarCicloRequest inValue = new ooiasoft.CicloWS.insertarCicloRequest();
            inValue.ciclo = ciclo;
            return ((ooiasoft.CicloWS.CicloWS)(this)).insertarCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CicloWS.eliminarCicloResponse ooiasoft.CicloWS.CicloWS.eliminarCiclo(ooiasoft.CicloWS.eliminarCicloRequest request) {
            return base.Channel.eliminarCiclo(request);
        }
        
        public int eliminarCiclo(int idCiclo) {
            ooiasoft.CicloWS.eliminarCicloRequest inValue = new ooiasoft.CicloWS.eliminarCicloRequest();
            inValue.idCiclo = idCiclo;
            ooiasoft.CicloWS.eliminarCicloResponse retVal = ((ooiasoft.CicloWS.CicloWS)(this)).eliminarCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CicloWS.eliminarCicloResponse> ooiasoft.CicloWS.CicloWS.eliminarCicloAsync(ooiasoft.CicloWS.eliminarCicloRequest request) {
            return base.Channel.eliminarCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CicloWS.eliminarCicloResponse> eliminarCicloAsync(int idCiclo) {
            ooiasoft.CicloWS.eliminarCicloRequest inValue = new ooiasoft.CicloWS.eliminarCicloRequest();
            inValue.idCiclo = idCiclo;
            return ((ooiasoft.CicloWS.CicloWS)(this)).eliminarCicloAsync(inValue);
        }
    }
}
