//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ooiasoft.CitaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", ConfigurationName="CitaWS.CitaWS")]
    public interface CitaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDeAlumnoPorCicloFechaPerso" +
            "nalRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDeAlumnoPorCicloFechaPerso" +
            "nalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse listarCitasDeAlumnoPorCicloFechaPersonal(ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDeAlumnoPorCicloFechaPerso" +
            "nalRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDeAlumnoPorCicloFechaPerso" +
            "nalResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse> listarCitasDeAlumnoPorCicloFechaPersonalAsync(ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDePersonalPorCicloFechaAlu" +
            "mnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDePersonalPorCicloFechaAlu" +
            "mnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse listarCitasDePersonalPorCicloFechaAlumno(ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDePersonalPorCicloFechaAlu" +
            "mnoRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarCitasDePersonalPorCicloFechaAlu" +
            "mnoResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse> listarCitasDePersonalPorCicloFechaAlumnoAsync(ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.insertarCitaResponse insertarCita(ooiasoft.CitaWS.insertarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarCitaResponse> insertarCitaAsync(ooiasoft.CitaWS.insertarCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.modificarCitaResponse modificarCita(ooiasoft.CitaWS.modificarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarCitaResponse> modificarCitaAsync(ooiasoft.CitaWS.modificarCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.eliminarCitaResponse eliminarCita(ooiasoft.CitaWS.eliminarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarCitaResponse> eliminarCitaAsync(ooiasoft.CitaWS.eliminarCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarMotivoCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.insertarMotivoCitaResponse insertarMotivoCita(ooiasoft.CitaWS.insertarMotivoCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/insertarMotivoCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarMotivoCitaResponse> insertarMotivoCitaAsync(ooiasoft.CitaWS.insertarMotivoCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarMotivoCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.eliminarMotivoCitaResponse eliminarMotivoCita(ooiasoft.CitaWS.eliminarMotivoCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/eliminarMotivoCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarMotivoCitaResponse> eliminarMotivoCitaAsync(ooiasoft.CitaWS.eliminarMotivoCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarMotivoCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.modificarMotivoCitaResponse modificarMotivoCita(ooiasoft.CitaWS.modificarMotivoCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarMotivoCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/modificarMotivoCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarMotivoCitaResponse> modificarMotivoCitaAsync(ooiasoft.CitaWS.modificarMotivoCitaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarMotivosCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarMotivosCitaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ooiasoft.CitaWS.listarMotivosCitaResponse listarMotivosCita(ooiasoft.CitaWS.listarMotivosCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarMotivosCitaRequest", ReplyAction="http://services.ooiasoft.pucp.edu.pe/CitaWS/listarMotivosCitaResponse")]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarMotivosCitaResponse> listarMotivosCitaAsync(ooiasoft.CitaWS.listarMotivosCitaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class cita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno alumnoField;
        
        private bool asistioField;
        
        private ciclo cicloField;
        
        private bool estadoField;
        
        private System.DateTime fechaAtencionField;
        
        private bool fechaAtencionFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int horaField;
        
        private int idCitaField;
        
        private motivoCita motivoCitaField;
        
        private personalCitas personalCitasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool asistio {
            get {
                return this.asistioField;
            }
            set {
                this.asistioField = value;
                this.RaisePropertyChanged("asistio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaAtencion {
            get {
                return this.fechaAtencionField;
            }
            set {
                this.fechaAtencionField = value;
                this.RaisePropertyChanged("fechaAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAtencionSpecified {
            get {
                return this.fechaAtencionFieldSpecified;
            }
            set {
                this.fechaAtencionFieldSpecified = value;
                this.RaisePropertyChanged("fechaAtencionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public motivoCita motivoCita {
            get {
                return this.motivoCitaField;
            }
            set {
                this.motivoCitaField = value;
                this.RaisePropertyChanged("motivoCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public personalCitas personalCitas {
            get {
                return this.personalCitasField;
            }
            set {
                this.personalCitasField = value;
                this.RaisePropertyChanged("personalCitas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumno : persona {
        
        private double cRAESTField;
        
        private int cantCiclosField;
        
        private int cantCursosAprobadosField;
        
        private double cantidadCreditosAprobadosField;
        
        private alumnoCiclo[] ciclosField;
        
        private int escalaPagoField;
        
        private especialidad especialidadField;
        
        private double promedioPonderadoField;
        
        private tipoAlumno tipoField;
        
        private bool tipoFieldSpecified;
        
        private double totalCreditosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double CRAEST {
            get {
                return this.cRAESTField;
            }
            set {
                this.cRAESTField = value;
                this.RaisePropertyChanged("CRAEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantCiclos {
            get {
                return this.cantCiclosField;
            }
            set {
                this.cantCiclosField = value;
                this.RaisePropertyChanged("cantCiclos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantCursosAprobados {
            get {
                return this.cantCursosAprobadosField;
            }
            set {
                this.cantCursosAprobadosField = value;
                this.RaisePropertyChanged("cantCursosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double cantidadCreditosAprobados {
            get {
                return this.cantidadCreditosAprobadosField;
            }
            set {
                this.cantidadCreditosAprobadosField = value;
                this.RaisePropertyChanged("cantidadCreditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ciclos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public alumnoCiclo[] ciclos {
            get {
                return this.ciclosField;
            }
            set {
                this.ciclosField = value;
                this.RaisePropertyChanged("ciclos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int escalaPago {
            get {
                return this.escalaPagoField;
            }
            set {
                this.escalaPagoField = value;
                this.RaisePropertyChanged("escalaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double promedioPonderado {
            get {
                return this.promedioPonderadoField;
            }
            set {
                this.promedioPonderadoField = value;
                this.RaisePropertyChanged("promedioPonderado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoAlumno tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double totalCreditos {
            get {
                return this.totalCreditosField;
            }
            set {
                this.totalCreditosField = value;
                this.RaisePropertyChanged("totalCreditos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumnoCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double cRAESTField;
        
        private int cantidadCursosAprobadosField;
        
        private ciclo cicloField;
        
        private double creditosAprobadosField;
        
        private double creditosTotalesField;
        
        private alumnoCursoCiclo[] cursosField;
        
        private bool estadoField;
        
        private int idAlumnoCicloField;
        
        private double promedioPonderadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double CRAEST {
            get {
                return this.cRAESTField;
            }
            set {
                this.cRAESTField = value;
                this.RaisePropertyChanged("CRAEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadCursosAprobados {
            get {
                return this.cantidadCursosAprobadosField;
            }
            set {
                this.cantidadCursosAprobadosField = value;
                this.RaisePropertyChanged("cantidadCursosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ciclo ciclo {
            get {
                return this.cicloField;
            }
            set {
                this.cicloField = value;
                this.RaisePropertyChanged("ciclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double creditosAprobados {
            get {
                return this.creditosAprobadosField;
            }
            set {
                this.creditosAprobadosField = value;
                this.RaisePropertyChanged("creditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double creditosTotales {
            get {
                return this.creditosTotalesField;
            }
            set {
                this.creditosTotalesField = value;
                this.RaisePropertyChanged("creditosTotales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public alumnoCursoCiclo[] cursos {
            get {
                return this.cursosField;
            }
            set {
                this.cursosField = value;
                this.RaisePropertyChanged("cursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idAlumnoCiclo {
            get {
                return this.idAlumnoCicloField;
            }
            set {
                this.idAlumnoCicloField = value;
                this.RaisePropertyChanged("idAlumnoCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double promedioPonderado {
            get {
                return this.promedioPonderadoField;
            }
            set {
                this.promedioPonderadoField = value;
                this.RaisePropertyChanged("promedioPonderado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCicloField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCiclo {
            get {
                return this.idCicloField;
            }
            set {
                this.idCicloField = value;
                this.RaisePropertyChanged("idCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class motivoCita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort abreviaturaField;
        
        private string descripcionField;
        
        private bool estadoField;
        
        private int idMotivoField;
        
        private tipoCita tipoCitaField;
        
        private bool tipoCitaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort abreviatura {
            get {
                return this.abreviaturaField;
            }
            set {
                this.abreviaturaField = value;
                this.RaisePropertyChanged("abreviatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idMotivo {
            get {
                return this.idMotivoField;
            }
            set {
                this.idMotivoField = value;
                this.RaisePropertyChanged("idMotivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoCita tipoCita {
            get {
                return this.tipoCitaField;
            }
            set {
                this.tipoCitaField = value;
                this.RaisePropertyChanged("tipoCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoCitaSpecified {
            get {
                return this.tipoCitaFieldSpecified;
            }
            set {
                this.tipoCitaFieldSpecified = value;
                this.RaisePropertyChanged("tipoCitaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoCita {
        
        /// <remarks/>
        Psicologico,
        
        /// <remarks/>
        Academico,
        
        /// <remarks/>
        Vocacional,
        
        /// <remarks/>
        Reintegracion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class evaluacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comentariosField;
        
        private bool estadoField;
        
        private int idEvaluacionField;
        
        private int notaField;
        
        private int numEvaluacionField;
        
        private tipoEvaluacion tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEvaluacion {
            get {
                return this.idEvaluacionField;
            }
            set {
                this.idEvaluacionField = value;
                this.RaisePropertyChanged("idEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
                this.RaisePropertyChanged("nota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numEvaluacion {
            get {
                return this.numEvaluacionField;
            }
            set {
                this.numEvaluacionField = value;
                this.RaisePropertyChanged("numEvaluacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoEvaluacion tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoEvaluacion {
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        EX,
        
        /// <remarks/>
        TA,
        
        /// <remarks/>
        PC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private bool estadoField;
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private double creditosField;
        
        private especialidad especialidadField;
        
        private bool estadoField;
        
        private int idCursoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class alumnoCursoCiclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private curso cursoField;
        
        private tipoECTS escalaField;
        
        private bool escalaFieldSpecified;
        
        private bool estadoField;
        
        private evaluacion[] evaluacionesField;
        
        private int idAlumnoCursoCicloField;
        
        private double notaFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoECTS escala {
            get {
                return this.escalaField;
            }
            set {
                this.escalaField = value;
                this.RaisePropertyChanged("escala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool escalaSpecified {
            get {
                return this.escalaFieldSpecified;
            }
            set {
                this.escalaFieldSpecified = value;
                this.RaisePropertyChanged("escalaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evaluaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public evaluacion[] evaluaciones {
            get {
                return this.evaluacionesField;
            }
            set {
                this.evaluacionesField = value;
                this.RaisePropertyChanged("evaluaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idAlumnoCursoCiclo {
            get {
                return this.idAlumnoCursoCicloField;
            }
            set {
                this.idAlumnoCursoCicloField = value;
                this.RaisePropertyChanged("idAlumnoCursoCiclo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double notaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
                this.RaisePropertyChanged("notaFinal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoECTS {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        FX,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        NT,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroOOIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personalCitas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPUCPField;
        
        private string correoField;
        
        private string dNIField;
        
        private int edadField;
        
        private bool estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombreCompletoField;
        
        private string passwordField;
        
        private ushort sexoField;
        
        private string telefonoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personalCitas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class miembroOOIA : persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public partial class personalCitas : miembroOOIA {
        
        private int horasSemanalesField;
        
        private double rendimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int horasSemanales {
            get {
                return this.horasSemanalesField;
            }
            set {
                this.horasSemanalesField = value;
                this.RaisePropertyChanged("horasSemanales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double rendimiento {
            get {
                return this.rendimientoField;
            }
            set {
                this.rendimientoField = value;
                this.RaisePropertyChanged("rendimiento");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/")]
    public enum tipoAlumno {
        
        /// <remarks/>
        Regular,
        
        /// <remarks/>
        NoRegular,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCitasDeAlumnoPorCicloFechaPersonal", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCitasDeAlumnoPorCicloFechaPersonalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ciclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombrePersonal;
        
        public listarCitasDeAlumnoPorCicloFechaPersonalRequest() {
        }
        
        public listarCitasDeAlumnoPorCicloFechaPersonalRequest(int idAlumno, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombrePersonal) {
            this.idAlumno = idAlumno;
            this.ciclo = ciclo;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
            this.nombrePersonal = nombrePersonal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCitasDeAlumnoPorCicloFechaPersonalResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCitasDeAlumnoPorCicloFechaPersonalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.cita[] @return;
        
        public listarCitasDeAlumnoPorCicloFechaPersonalResponse() {
        }
        
        public listarCitasDeAlumnoPorCicloFechaPersonalResponse(ooiasoft.CitaWS.cita[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCitasDePersonalPorCicloFechaAlumno", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCitasDePersonalPorCicloFechaAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersonal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ciclo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreAlumno;
        
        public listarCitasDePersonalPorCicloFechaAlumnoRequest() {
        }
        
        public listarCitasDePersonalPorCicloFechaAlumnoRequest(int idPersonal, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombreAlumno) {
            this.idPersonal = idPersonal;
            this.ciclo = ciclo;
            this.fechaIni = fechaIni;
            this.fechaFin = fechaFin;
            this.nombreAlumno = nombreAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCitasDePersonalPorCicloFechaAlumnoResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCitasDePersonalPorCicloFechaAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.cita[] @return;
        
        public listarCitasDePersonalPorCicloFechaAlumnoResponse() {
        }
        
        public listarCitasDePersonalPorCicloFechaAlumnoResponse(ooiasoft.CitaWS.cita[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.cita cita;
        
        public insertarCitaRequest() {
        }
        
        public insertarCitaRequest(ooiasoft.CitaWS.cita cita) {
            this.cita = cita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCitaResponse() {
        }
        
        public insertarCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.cita cita;
        
        public modificarCitaRequest() {
        }
        
        public modificarCitaRequest(ooiasoft.CitaWS.cita cita) {
            this.cita = cita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCitaResponse() {
        }
        
        public modificarCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCita;
        
        public eliminarCitaRequest() {
        }
        
        public eliminarCitaRequest(int idCita) {
            this.idCita = idCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCitaResponse() {
        }
        
        public eliminarCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMotivoCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMotivoCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.motivoCita motivoCita;
        
        public insertarMotivoCitaRequest() {
        }
        
        public insertarMotivoCitaRequest(ooiasoft.CitaWS.motivoCita motivoCita) {
            this.motivoCita = motivoCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMotivoCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMotivoCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMotivoCitaResponse() {
        }
        
        public insertarMotivoCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMotivoCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMotivoCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMotivoCita;
        
        public eliminarMotivoCitaRequest() {
        }
        
        public eliminarMotivoCitaRequest(int idMotivoCita) {
            this.idMotivoCita = idMotivoCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMotivoCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMotivoCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMotivoCitaResponse() {
        }
        
        public eliminarMotivoCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMotivoCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMotivoCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.motivoCita motivoCita;
        
        public modificarMotivoCitaRequest() {
        }
        
        public modificarMotivoCitaRequest(ooiasoft.CitaWS.motivoCita motivoCita) {
            this.motivoCita = motivoCita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMotivoCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarMotivoCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMotivoCitaResponse() {
        }
        
        public modificarMotivoCitaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMotivosCita", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMotivosCitaRequest {
        
        public listarMotivosCitaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMotivosCitaResponse", WrapperNamespace="http://services.ooiasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMotivosCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ooiasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ooiasoft.CitaWS.motivoCita[] @return;
        
        public listarMotivosCitaResponse() {
        }
        
        public listarMotivosCitaResponse(ooiasoft.CitaWS.motivoCita[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CitaWSChannel : ooiasoft.CitaWS.CitaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CitaWSClient : System.ServiceModel.ClientBase<ooiasoft.CitaWS.CitaWS>, ooiasoft.CitaWS.CitaWS {
        
        public CitaWSClient() {
        }
        
        public CitaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CitaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse ooiasoft.CitaWS.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonal(ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest request) {
            return base.Channel.listarCitasDeAlumnoPorCicloFechaPersonal(request);
        }
        
        public ooiasoft.CitaWS.cita[] listarCitasDeAlumnoPorCicloFechaPersonal(int idAlumno, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombrePersonal) {
            ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest inValue = new ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest();
            inValue.idAlumno = idAlumno;
            inValue.ciclo = ciclo;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.nombrePersonal = nombrePersonal;
            ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).listarCitasDeAlumnoPorCicloFechaPersonal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse> ooiasoft.CitaWS.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalAsync(ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest request) {
            return base.Channel.listarCitasDeAlumnoPorCicloFechaPersonalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalResponse> listarCitasDeAlumnoPorCicloFechaPersonalAsync(int idAlumno, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombrePersonal) {
            ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest inValue = new ooiasoft.CitaWS.listarCitasDeAlumnoPorCicloFechaPersonalRequest();
            inValue.idAlumno = idAlumno;
            inValue.ciclo = ciclo;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.nombrePersonal = nombrePersonal;
            return ((ooiasoft.CitaWS.CitaWS)(this)).listarCitasDeAlumnoPorCicloFechaPersonalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse ooiasoft.CitaWS.CitaWS.listarCitasDePersonalPorCicloFechaAlumno(ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest request) {
            return base.Channel.listarCitasDePersonalPorCicloFechaAlumno(request);
        }
        
        public ooiasoft.CitaWS.cita[] listarCitasDePersonalPorCicloFechaAlumno(int idPersonal, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombreAlumno) {
            ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest inValue = new ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest();
            inValue.idPersonal = idPersonal;
            inValue.ciclo = ciclo;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.nombreAlumno = nombreAlumno;
            ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).listarCitasDePersonalPorCicloFechaAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse> ooiasoft.CitaWS.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoAsync(ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest request) {
            return base.Channel.listarCitasDePersonalPorCicloFechaAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoResponse> listarCitasDePersonalPorCicloFechaAlumnoAsync(int idPersonal, string ciclo, System.DateTime fechaIni, System.DateTime fechaFin, string nombreAlumno) {
            ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest inValue = new ooiasoft.CitaWS.listarCitasDePersonalPorCicloFechaAlumnoRequest();
            inValue.idPersonal = idPersonal;
            inValue.ciclo = ciclo;
            inValue.fechaIni = fechaIni;
            inValue.fechaFin = fechaFin;
            inValue.nombreAlumno = nombreAlumno;
            return ((ooiasoft.CitaWS.CitaWS)(this)).listarCitasDePersonalPorCicloFechaAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.insertarCitaResponse ooiasoft.CitaWS.CitaWS.insertarCita(ooiasoft.CitaWS.insertarCitaRequest request) {
            return base.Channel.insertarCita(request);
        }
        
        public int insertarCita(ooiasoft.CitaWS.cita cita) {
            ooiasoft.CitaWS.insertarCitaRequest inValue = new ooiasoft.CitaWS.insertarCitaRequest();
            inValue.cita = cita;
            ooiasoft.CitaWS.insertarCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).insertarCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarCitaResponse> ooiasoft.CitaWS.CitaWS.insertarCitaAsync(ooiasoft.CitaWS.insertarCitaRequest request) {
            return base.Channel.insertarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarCitaResponse> insertarCitaAsync(ooiasoft.CitaWS.cita cita) {
            ooiasoft.CitaWS.insertarCitaRequest inValue = new ooiasoft.CitaWS.insertarCitaRequest();
            inValue.cita = cita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).insertarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.modificarCitaResponse ooiasoft.CitaWS.CitaWS.modificarCita(ooiasoft.CitaWS.modificarCitaRequest request) {
            return base.Channel.modificarCita(request);
        }
        
        public int modificarCita(ooiasoft.CitaWS.cita cita) {
            ooiasoft.CitaWS.modificarCitaRequest inValue = new ooiasoft.CitaWS.modificarCitaRequest();
            inValue.cita = cita;
            ooiasoft.CitaWS.modificarCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).modificarCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarCitaResponse> ooiasoft.CitaWS.CitaWS.modificarCitaAsync(ooiasoft.CitaWS.modificarCitaRequest request) {
            return base.Channel.modificarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarCitaResponse> modificarCitaAsync(ooiasoft.CitaWS.cita cita) {
            ooiasoft.CitaWS.modificarCitaRequest inValue = new ooiasoft.CitaWS.modificarCitaRequest();
            inValue.cita = cita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).modificarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.eliminarCitaResponse ooiasoft.CitaWS.CitaWS.eliminarCita(ooiasoft.CitaWS.eliminarCitaRequest request) {
            return base.Channel.eliminarCita(request);
        }
        
        public int eliminarCita(int idCita) {
            ooiasoft.CitaWS.eliminarCitaRequest inValue = new ooiasoft.CitaWS.eliminarCitaRequest();
            inValue.idCita = idCita;
            ooiasoft.CitaWS.eliminarCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).eliminarCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarCitaResponse> ooiasoft.CitaWS.CitaWS.eliminarCitaAsync(ooiasoft.CitaWS.eliminarCitaRequest request) {
            return base.Channel.eliminarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarCitaResponse> eliminarCitaAsync(int idCita) {
            ooiasoft.CitaWS.eliminarCitaRequest inValue = new ooiasoft.CitaWS.eliminarCitaRequest();
            inValue.idCita = idCita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).eliminarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.insertarMotivoCitaResponse ooiasoft.CitaWS.CitaWS.insertarMotivoCita(ooiasoft.CitaWS.insertarMotivoCitaRequest request) {
            return base.Channel.insertarMotivoCita(request);
        }
        
        public int insertarMotivoCita(ooiasoft.CitaWS.motivoCita motivoCita) {
            ooiasoft.CitaWS.insertarMotivoCitaRequest inValue = new ooiasoft.CitaWS.insertarMotivoCitaRequest();
            inValue.motivoCita = motivoCita;
            ooiasoft.CitaWS.insertarMotivoCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).insertarMotivoCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarMotivoCitaResponse> ooiasoft.CitaWS.CitaWS.insertarMotivoCitaAsync(ooiasoft.CitaWS.insertarMotivoCitaRequest request) {
            return base.Channel.insertarMotivoCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.insertarMotivoCitaResponse> insertarMotivoCitaAsync(ooiasoft.CitaWS.motivoCita motivoCita) {
            ooiasoft.CitaWS.insertarMotivoCitaRequest inValue = new ooiasoft.CitaWS.insertarMotivoCitaRequest();
            inValue.motivoCita = motivoCita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).insertarMotivoCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.eliminarMotivoCitaResponse ooiasoft.CitaWS.CitaWS.eliminarMotivoCita(ooiasoft.CitaWS.eliminarMotivoCitaRequest request) {
            return base.Channel.eliminarMotivoCita(request);
        }
        
        public int eliminarMotivoCita(int idMotivoCita) {
            ooiasoft.CitaWS.eliminarMotivoCitaRequest inValue = new ooiasoft.CitaWS.eliminarMotivoCitaRequest();
            inValue.idMotivoCita = idMotivoCita;
            ooiasoft.CitaWS.eliminarMotivoCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).eliminarMotivoCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarMotivoCitaResponse> ooiasoft.CitaWS.CitaWS.eliminarMotivoCitaAsync(ooiasoft.CitaWS.eliminarMotivoCitaRequest request) {
            return base.Channel.eliminarMotivoCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.eliminarMotivoCitaResponse> eliminarMotivoCitaAsync(int idMotivoCita) {
            ooiasoft.CitaWS.eliminarMotivoCitaRequest inValue = new ooiasoft.CitaWS.eliminarMotivoCitaRequest();
            inValue.idMotivoCita = idMotivoCita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).eliminarMotivoCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.modificarMotivoCitaResponse ooiasoft.CitaWS.CitaWS.modificarMotivoCita(ooiasoft.CitaWS.modificarMotivoCitaRequest request) {
            return base.Channel.modificarMotivoCita(request);
        }
        
        public int modificarMotivoCita(ooiasoft.CitaWS.motivoCita motivoCita) {
            ooiasoft.CitaWS.modificarMotivoCitaRequest inValue = new ooiasoft.CitaWS.modificarMotivoCitaRequest();
            inValue.motivoCita = motivoCita;
            ooiasoft.CitaWS.modificarMotivoCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).modificarMotivoCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarMotivoCitaResponse> ooiasoft.CitaWS.CitaWS.modificarMotivoCitaAsync(ooiasoft.CitaWS.modificarMotivoCitaRequest request) {
            return base.Channel.modificarMotivoCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.modificarMotivoCitaResponse> modificarMotivoCitaAsync(ooiasoft.CitaWS.motivoCita motivoCita) {
            ooiasoft.CitaWS.modificarMotivoCitaRequest inValue = new ooiasoft.CitaWS.modificarMotivoCitaRequest();
            inValue.motivoCita = motivoCita;
            return ((ooiasoft.CitaWS.CitaWS)(this)).modificarMotivoCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ooiasoft.CitaWS.listarMotivosCitaResponse ooiasoft.CitaWS.CitaWS.listarMotivosCita(ooiasoft.CitaWS.listarMotivosCitaRequest request) {
            return base.Channel.listarMotivosCita(request);
        }
        
        public ooiasoft.CitaWS.motivoCita[] listarMotivosCita() {
            ooiasoft.CitaWS.listarMotivosCitaRequest inValue = new ooiasoft.CitaWS.listarMotivosCitaRequest();
            ooiasoft.CitaWS.listarMotivosCitaResponse retVal = ((ooiasoft.CitaWS.CitaWS)(this)).listarMotivosCita(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ooiasoft.CitaWS.listarMotivosCitaResponse> ooiasoft.CitaWS.CitaWS.listarMotivosCitaAsync(ooiasoft.CitaWS.listarMotivosCitaRequest request) {
            return base.Channel.listarMotivosCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ooiasoft.CitaWS.listarMotivosCitaResponse> listarMotivosCitaAsync() {
            ooiasoft.CitaWS.listarMotivosCitaRequest inValue = new ooiasoft.CitaWS.listarMotivosCitaRequest();
            return ((ooiasoft.CitaWS.CitaWS)(this)).listarMotivosCitaAsync(inValue);
        }
    }
}
